name: Publish
"on":
  push:
    branches:
      - main
    paths:
      - RELEASES.md
jobs:
  publish:
    uses: hathora/cloud-sdk-typescript/.github/workflows/speakeasy/sdk-publish.yaml
    with:
      create_release: true
      publish_typescript: true
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
